# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-12 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sign_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.IntegerField(max_length=5)),
                ('shift', models.CharField(max_length=20)),
                ('mob_no', models.CharField(max_length=10)),
                ('Password', models.CharField(max_length=20)),
                ('confrom_pass', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='login',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attend.Sign_details'),
        ),
    ]
